### ISSUE TITLE
Update docs and demos

### ISSUE THREAD

**Issue by maktarsis** [storeon/angular#16]
It does not need many words

**Comment by ai** [comment]
What exactly do you want to change?

**Comment by maktarsis** [comment]
Stackblitz demo and readme are not synced.
We had a short conversation with @irustm about that

Stackblitz shows a bit different api
`const { dispatch, changes } = this.ngstoreon.useStoreon('count');`
while readme has 
` this.changes = this.ngstoreon.useStoreon('count');`

I recommend adding a few slices in the example
It will be more obvious for me to understand how to work with storeon in angular components

**Comment by irustm** [comment]
I update `@storeon/angular` to v0.2.0 
and Stackblitz demo too

**Comment by irustm** [comment]
demo with angular ivy will be updated after #15 issue is solved
