### ISSUE TITLE
Opt for npm or yarn, package-lock.json or yarn.lock

### ISSUE THREAD

**Issue by ruimarques** [storeon/angular#35]
Currently this project repo has both `package-lock.json` and `yarn.lock`

`yarn` complains about presence of `package-lock.json`.

Travis CI seems to use `yarn` for package install.

Not sure if we can, for instance, remove `package-lock.json` without undesired consequences?

**Comment by irustm** [comment]
Yeah, we should leave one.

I don't think we need yarn anymore.
