### ISSUE TITLE
Move to Storeon org

### ISSUE THREAD

**Issue by ai** [storeon/angular#4]
Do you want to move under `storeon/ng-storeon` or `storeon/ng` GitHub and npm organization?

You will need to enable 2FA on GitHub and npm for that.

**Comment by irustm** [comment]
Thank you for that.

I would like to move this repository to the storeon organization `storeon/ng-storeon`

and npm `@storeon/angular`

I've enabled 2FA everywhere

**Comment by ai** [comment]
Should we use the same name everywhere? `storeon/angular` on GitHub and `storeon/angular` on npm?

**Comment by irustm** [comment]
Yeah, that's better.

**Comment by ai** [comment]
I sent you invites. Ping me when you moved the project.

**Comment by irustm** [comment]
@ai done

**Comment by ai** [comment]
Perfect. Now change project name in `package.json` make a release with `npx clean-publish --access=public` (`clean-publish` reduces npm package size to make `node_modules` smaller).

**Comment by irustm** [comment]
I use ng-packagr. tool uses in Angular CLI.

so the npm is going to be a clean version. and package.json in the npm looks like this: https://github.com/storeon/angular/blob/master/projects/ng-storeon/package.json

**Comment by ai** [comment]
> I use ng-packagr. tool uses in Angular CLI.

Not a problem :+1: Just pass `--access=public` or whatever API is in your tool

**Comment by irustm** [comment]
done

**Comment by ai** [comment]
Do you have a Twitter account to mention you in the tweet?

**Comment by irustm** [comment]
Yeah, thanks!

https://twitter.com/irustm
